name: notesapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  page_transition: ^2.2.1
  http: ^1.3.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flutter_localizations: true

  assets:
    enabled: true
    package_parameter_enabled: true

  # Removed the colors section since we don't have colors.xml yet

  fonts:
    enabled: true
